optimization:
  rate: 100
  multiagent_topics_pre: /uavs/agent_
  visibility_matrix_topic_post: /visibility_matrix
  camera_pose_topic_post: /uav_odometry/odometry
  rotation_topic: /uavs/formation/update
  rviz_topic: occupancy_grid
  imbalance_topic: imbalance_factor
  rviz_publish: false
  angle_step: 0.01
  proportional_gain: 0.013
  probability_gain: 0.1
