optimization:
  rate: 20
  visibility_matrix_builder:
    cell_size: 0.1
    global_region:
      x_min: -10
      x_max: 30
      y_min: -10
      y_max: 10
    local_region:
      x_min: 0
      x_max: 10
      y_min: -5
      y_max: 5