visibility_matrix_builder:
  rate: 20
  publish_rviz: false
  cell_size: 0.2
  global_region:
    x_min: -20
    x_max: 50
    y_min: -20
    y_max: 20
  local_region:
    x_min: -5
    x_max: 5
    y_min: -5
    y_max: 5